SELECT TO_NUMBER(TO_CHAR(START_DATE, 'FMMM')) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM-dd') BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
AND CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYY-MM-dd') BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY TO_CHAR(START_DATE, 'FMMM'), CAR_ID
    HAVING COUNT(*) = 0
)
AND TO_CHAR(start_date, 'YYYY-MM') in ('2022-08', '2022-09', '2022-10')
GROUP BY TO_CHAR(START_DATE, 'FMMM'), CAR_ID
ORDER BY 1 ASC, 2 DESC